#!/usr/bin/env bash

set -eo pipefail

INPUT=""
OUTFILE=""
TEMPFILE=""

main() {
  parse_args "$@"
  # TODO: Try to minimize dependencies: sed, grep, cat, see bash bible
  TEMPFILE=$(mktemp "/tmp/gatsh.XXXXXXX")
  local root
  root=$(realpath "$INPUT")
  result=$(load_file "$root")
  if [[ -z "$OUTFILE" ]]; then 
    echo "$result" 
  else 
    echo "$result" > "$OUTFILE"
  fi
}

parse_args() {
  local positional=()
  while [[ $# -gt 0 ]]
  do
    key="$1"
    case $key in
      -o|--outfile)
        [[ $# -lt 2 ]] && die "Missing value for optional argument '$key'" 1
        OUTFILE="$2"
        shift
        shift
        ;;
      -h|--help)
        help && exit 0
        ;;
      *)
        positional+=("$1")
        shift
        ;;
    esac
  done
  set -- "${positional[@]}"

  if [[ ${#positional[@]} -ne 1 ]]; then
     HELP=1
     die "Missing value for non-optional argument 'file'" 1
  fi
  INPUT=$1
  if [[ ! -f "$INPUT" ]]; then die "The file '$INPUT' does not exist!" 0; fi
  
  validate_options
}

validate_options() {
  if [[ -n "$OUTFILE" ]]; then 
    local directory=
    directory=$(dirname "$OUTFILE")
    if [[ ! -d "$directory" ]]; then  die "Invalid output file '$OUTFILE'. Directory '$directory' does not exist" 1; fi
  fi
}

die() {
  local exit_code=$2
  [[ -n "$exit_code" ]] || exit_code=1
  [[ "$HELP" = 1 ]] && help >&2
  echo "$1" >&2
  exit ${exit_code}
}

help() {
  cat <<EOF
Usage: gatsh [OPTIONS] <file>

Recursively concatinate scripts referenced in file to standard output. 

Options: 
  -o|--outfile  Redirects the output to the specified file
  -h|--help     Displays the usage information

Examples: 
  gatsh main.sh

EOF
}

load_file() {
  local file="$1"
  echo "$file" >> "$TEMPFILE"
  local contents
  contents=$(cat "$file") 
  contents=$(inline_sourced "$file" "$contents")
  echo "$contents"
}

inline_sourced() {
  # TODO: Rip this apart so its more testable, then make sure grep matches all patterns
  local root="$1"
  local contents="$2"
  local sources
  # Get all lines where other files are sourced. If no such lines occur we can return this
  # files contents as is, because there is nothing to inline.
  sources=$(echo "$contents" | grep -e '^\w*source\s.*' -e '^\w*\.\s.*')
  [ -z "$sources" ] && { echo "$contents"; return; }
  local sourced_contents
  while read -r line; do
    sourced_contents=$(load_sourced_files "$root" "$line")
    # Replace the source line with the contents of the sourced files. Remove all other occurences of 
    # that line as well, because there's no need to process them 
    contents=${contents/"$line"/"$sourced_contents"}
    contents=${contents//"$line"}
  done <<< "$sources"
  echo "$contents"
}

load_sourced_files() {
  # TODO: Rip this apart so its more testable, then make sure grep matches all patterns
  local root="$1"
  local source_line="$2"
  local sources
  sources=$(get_individual_sources "$source_line")
  local sources_contents=()
  local content
  while read -r source; do
    sourced_path=$(get_sourced_path "$root" "$source")
    # Check that the file being imported was not already imported, if it was just skip
    readarray imported_files < "$TEMPFILE"
    [[ ${imported_files[*]} == *"$sourced_path"* ]] && continue
    
    # If the source does not exists we need to exit, because nothing good will come of this
    [[ ! -f "$sourced_path" ]] && die "ERROR: Failed to parse '$root'. The source file $source does not exist" 0
      
    content=$(load_file "$sourced_path")

    # Sanitize content: Remove shebang and leading/trailing newlines
    # See https://stackoverflow.com/a/7359879/2553104 and https://stackoverflow.com/a/1935132/2553104
    content=$(echo "$content" | sed '/^#!/d' | sed -e :a -e '/./,$!d;/^\n*$/{$d;N;};/\n$/ba' )
    sources_contents+=("$content")
  done <<< "$sources"
  echo "${sources_contents[*]}"
}

# Get all files that occur within a single source statement.
#
# Example: 
# get_individual_sources lib1 lib2 yields lib1, lib2

get_individual_sources() {
  source_line="$1"
  echo "$source_line" \
    | cut -d' ' -f2- \
    | tr ' ' '\n'
}

# Resolve a given source to an absolute path
# 
# Parameters: 
#   $1 - The file from which requires the source. Must be in an existing directory
#   $2 - The path to the sourced file
# 
# Examples
#   get_sourced_path main.sh ../lib1 
# 
get_sourced_path() {
  local root="$1"
  local source="$2"
  clean_source
  local source_path
  # Get path relative to file which sources source
  source_path=$(cd "${root%/*}" && realpath "$source")
  echo "$source_path"
}

# Remove superfluous quotes from the given source
clean_source(){
  source="${source%\"}"
  source="${source#\"}"
  source="${source%\'}"
  source="${source#\'}"
}

handle_exit() {
  [[ -f "$TEMPFILE" ]] && rm "$TEMPFILE"
}

trap handle_exit ERR

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
  main "$@"
fi
